[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$major.$minor.$patch$prerelease"
version = "1.2.7"
version_files = [
    "package.json:version",
    "package-lock.json:version",
    ".cz.toml"
]
